name: Lint

on:
  push:
    branches: master
  pull_request:
    branches: '*'

jobs:
  lint_ts:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v1
    - name: Install node
      uses: actions/setup-node@v1
      with:
       node-version: '10.x'
    - name: Lint TypeScript
      run: |
        npm i && npm run lint

  lint_python:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v1
    - name: Install Python
      uses: actions/setup-python@v1
      with:
        python-version: '3.7'
        architecture: 'x64'
    - name: Install black
      run: python -m pip install black
    - name: Lint Python
      run: |
        black --check .
